version: '3.3'

 services:
  worker1:
     depends_on:
         - db
     image: mysql:5.7
     ports:
         - "3306:3306"
     restart: always
     environment:
         MYSQL_HOST: db:3306
	 MYSQL_DATABASE: reservasi
         MYSQL_USER: userawan
         MYSQL_PASSWORD: buayakecil
   networks:
     docker1:
       ipv4_address: 192.168.0.1

 services:
  worker2:
     depends_on:
         - db
     image: mysql:5.7
     ports:
         - "3306:3306"
     restart: always
     environment:
         MYSQL_HOST: db:3306
         MYSQL_DATABASE: reservasi
         MYSQL_USER: userawan
         MYSQL_PASSWORD: buayakecil
   networks:
     docker1:
       ipv4_address: 192.168.0.2

 services:
  worker3:
     depends_on:
         - db
     image: mysql:5.7
     ports:
         - "3306:3306"
     restart: always
     environment:
         MYSQL_HOST: db:3306
         MYSQL_DATABASE: reservasi
         MYSQL_USER: userawan
         MYSQL_PASSWORD: buayakecil
   networks:
     docker1:
       ipv4_address: 192.168.0.3

loadbalancer:
  image: nginx:stable-alpine
  depends_on:
    - worker1
    - worker2
    - worker3
  volumes:
   - ./mysite.template:/etc/nginx/conf.d/mysite.template
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

